#!/usr/bin/python

'''
Release script for imapclient
'''

import os
import sys
import imapclient

DIST_DIR = '../dist'

def fatal(msg):
    sys.stderr.write(msg+'\n')
    sys.exit(1)

os.system('rm -f *.pyc')

# Check for stale commits
if os.popen('svn status').readlines():
    fatal("Stale commits, please fix")

# Tag in svn
exitcode = os.system('svn cp '
    '-m "tagging imapclient "%s" '
    'file:///home/msmits/svnroot/trunk/imapclient '
    'file:///home/msmits/svnroot/tags/imapclient/$version ' % (
        imapclient.__version__))
if exitcode:
    sys.exit(2)

# Create distribution archives
os.system('python setup.py sdist -d %s --formats=gztar,zip' % DIST_DIR)

