name: Lint

# If a pull-request is pushed then cancel all previously running jobs related
# to that pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PY_COLORS: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - run: pip install --upgrade tox
      - name: Run black code formatter (https://black.readthedocs.io/en/stable/)
        run: tox -e black -- --check
